---
title: "Jess"
author: "Jessica Ozog"
date: "4/2/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Turtle Stranding : Set Up

```{r turtle set up}
# load packages
library(tidyverse)
library(tidyr)
library(lubridate)
library(dplyr)
library(cowplot)
library(ggplot2)
library(ggridges)
library(agricolae)
library(lubridate)
library(corrplot)
library(htmltools)
library(sf)
library(leaflet)
library(mapview)
library(RColorBrewer)
library(leafsync)
library(trend)
library(zoo)
library(Kendall)
library(tseries)
library(knitr)

# working directory and theme
getwd()
mytheme <- theme_bw() +
  theme(axis.text = element_text(color = "black"), 
        legend.position = "right")
theme_set(mytheme)

# read in the strandings data
Strandings <- read.csv("./Data/Processed/strandings_final.csv", stringsAsFactors = TRUE)
Turtle_Stranding_Data <- Strandings %>%
  filter(Family == "Turtles") %>%
  select(Family:longitude)
Turtle_Stranding_Data$Date <- as.Date(Turtle_Stranding_Data$Date, format = "%Y-%m-%d")

# read in the total strandings data
Strandings_Totals <- read.csv("./Data/Processed/strandings_totals.csv", stringsAsFactors = TRUE)
Turtle_Stranding_Totals <- Strandings_Totals %>%
  select(Year, Turtles_Total)

# turtle strandings summed by date
Turtle_Stranding_by_date <- Turtle_Stranding_Data %>%
                    group_by(Date) %>%
                    summarise(Total = n())
```

## Turtle Stranding: Exploratory Analysis

```{r turtle exploratory analysis}
summary(Turtle_Stranding_Data)

# plot of the turtle strandings by year
ggplot(Turtle_Stranding_Data) +
  geom_bar(aes(x = Year, fill = common_name)) +
  ylab("Count") +
  labs(title = "Total Sea Turtle Strandings per Year by Species") +
  scale_fill_discrete(name = "Sea Turtle Species", labels = c("Green (Chelonia mydas)", "Kemp's Ridley (Lepidochelys kempii)", "Leatherback (Dermochelys coriacea)", "Loggerhead (Caretta caretta)", "Unidentified Turtle"))

# plot of turtle strandings by month
ggplot(Turtle_Stranding_Data) +
  geom_bar(aes(x = Month, fill = common_name)) +
  ylab("Count") +
  labs(title = "Total Sea Turtle Strandings per Month by Species") + 
  scale_fill_discrete(name = "Sea Turtle Species", labels = c("Green (Chelonia mydas)", "Kemp's Ridley (Lepidochelys kempii)", "Leatherback (Dermochelys coriacea)", "Loggerhead (Caretta caretta)", "Unidentified Turtle")) +
  scale_x_discrete(name = "Month",
                   limits = c("Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"))
```

## Turtle Stranding: Spaital Analysis

```{r turtle spatial analysis}
# create spatial frame of turtle data
Turtle_sf <- Turtle_Stranding_Data %>%
  st_as_sf(coords = c("longitude", "latitude"), crs = 4326)
mapview(Turtle_sf)

# used UTM Zone 19 (data spans across UTM zone 18 and 19)
Turtle_sf_utm <- st_transform(Turtle_sf, 32619)
mapview(Turtle_sf_utm)

# find average lat and longs
avgLong_Turtle <- mean(Turtle_Stranding_Data$longitude)
avgLat_Turtle <- mean(Turtle_Stranding_Data$latitude)
avg_Turtle_coords <- data.frame(avgLong_Turtle, avgLat_Turtle)

# center point of the turtle strandings 
avg_Turtle_sf <- avg_Turtle_coords %>%
  st_as_sf(coords = c("avgLong_Turtle", "avgLat_Turtle"), crs = 4326)
avg_Turtle_sf_utm <- st_transform(avg_Turtle_sf, 32619)
mapview(avg_Turtle_sf_utm)

# find how far each stranding is from the mean stranding location
distance_matrix <- st_distance(Turtle_sf_utm, avg_Turtle_sf_utm, pairwise=T)
#Compute the mean of each row (each EPA site)
mean_distances <-  rowMeans(distance_matrix)
#Add as a column to the epa sites
Turtle_sf_utm  <-  Turtle_sf_utm %>% 
  bind_cols(mean_distance = mean_distances) 

# make a pretty map 
mapview(Turtle_sf_utm, zcol="mean_distance", layer.name = "Distance (m) from Mean Stranding Point")
```

## Turtle Stranding: Spaital Table

```{r turtle table}
# points within 20,000m
Turtle_20 <- Turtle_sf_utm %>%
  filter(mean_distance < 20000) %>%
  mutate(distance_group = "< 20,000")

# points between 20,000m - 40,000m
Turtle_20_40 <- Turtle_sf_utm %>%
  filter(mean_distance >= 20000 & mean_distance < 40000) %>%
  mutate(distance_group = "20,000 - 40,000")

# points between 40,000m - 60,000m
Turtle_40_60 <- Turtle_sf_utm %>%
  filter(mean_distance >= 40000 & mean_distance < 60000) %>%
  mutate(distance_group = "40,000 - 60,000")

# points between 60,000m - 80,000m
Turtle_60_80 <- Turtle_sf_utm %>%
  filter(mean_distance >= 60000 & mean_distance < 80000) %>%
  mutate(distance_group = "60,000 - 80,000")

# points between 80,000m - 100,000m
Turtle_80_100 <- Turtle_sf_utm %>%
  filter(mean_distance >= 80000 & mean_distance < 100000) %>%
  mutate(distance_group = "80,000 - 100,000")

# points between 100,000m - 120,000m
Turtle_100_120 <- Turtle_sf_utm %>%
  filter(mean_distance >= 100000 & mean_distance < 120000) %>%
  mutate(distance_group = "100,000 - 120,000")

# points between 120,000m - 140,000m
Turtle_120_140 <- Turtle_sf_utm %>%
  filter(mean_distance >= 120000 & mean_distance < 140000) %>%
  mutate(distance_group = "120,000 - 140,000")

# points between 140,000m - 160,000m
Turtle_140_160 <- Turtle_sf_utm %>%
  filter(mean_distance >= 140000 & mean_distance < 160000) %>%
  mutate(distance_group = "140,000 - 160,000")

# points greater than 160,000m
Turtle_160 <- Turtle_sf_utm %>%
  filter(mean_distance >= 160000) %>%
  mutate(distance_group = "> 160,000")

# row bind the distance dataframes
Turtle_sf_utm_final <- rbind(Turtle_20, Turtle_20_40,Turtle_40_60,
                             Turtle_60_80,Turtle_80_100,Turtle_100_120,
                             Turtle_120_140,Turtle_140_160,Turtle_160)

Turtle_distances <- Turtle_sf_utm_final %>%
  group_by(distance_group) %>%
  summarise(totals_by_distance = n()) %>%
  st_drop_geometry() %>%
  arrange(totals_by_distance)

kable(Turtle_distances)
```

## Turtle Stranding: Statistical Analysis

```{r turtles statistical analysis}
Turtle_Model <- lm(data = Turtle_Stranding_Totals, Turtles_Total ~ Year)
summary(Turtle_Model)
```

## Turtle Stranding: Time Series

```{r turtle time series}
# time series by year
Turtle_ts_yearly <- ts(Turtle_Stranding_by_date, start = c(1990,1), frequency = 1)

# time series by month
f_month <- month(first(Turtle_Stranding_by_date$Date))
f_year <- year(first(Turtle_Stranding_by_date$Date))
Turtle_ts_monthly <- ts(Turtle_Stranding_by_date$Total, 
                  start = c(f_year, f_month), 
                  frequency = 12)
# monthly decomposition 
Turtle_ts_monthly_decomp <- stl(Turtle_ts_monthly, s.window = "periodic")
plot(Turtle_ts_monthly_decomp)

# Trends
Turtle_ts_yearly_trend <- Kendall::SeasonalMannKendall(Turtle_ts_yearly)
summary(Turtle_ts_yearly_trend)

Turtle_ts_monthly_trend <- Kendall::SeasonalMannKendall(Turtle_ts_monthly)
summary(Turtle_ts_monthly_trend)
```

```
