---
title: "Data Exploration"
author: "Joshua Meza-Fidalgo, Jess Ozog & Britney Pepper"
date: '2022-04-02'
output: pdf_document
---

```{r Setup}
library(dplyr)
library(ggplot2)
library(tidyverse)

getwd()

mytheme <- theme_bw() +
  theme(axis.text = element_text(color = "black"), 
        legend.position = "right")
theme_set(mytheme)
```


```{r Data Prep}
Strandings_Final <- read.csv("../Data/Processed/strandings_final.csv", stringsAsFactors = TRUE)

Strandings_Final <- Strandings_Final %>%
  select(Family:longitude)
```


```{r Data Exploration}
class(Strandings_Final)

str(Strandings_Final)

colnames(Strandings_Final)

dim(Strandings_Final)

length(Strandings_Final)
```

```{r Data Exploration 2}
head(Strandings_Final)

tail(Strandings_Final)
```

```{r Data Summary}
summary(Strandings_Final)
```

```{r Visually Exploring Data}
ggplot(Strandings_Final) +
  geom_bar(aes(x = Family, fill = Family)) +
  ylab("Count") +
  labs(title = "Total Strandings per Family")

ggplot(Strandings_Final) +
  geom_bar(aes(x = Year, fill = Family)) +
  ylab("Count") +
  labs(title = "Total Strandings per Year")

ggplot(Strandings_Final) +
  geom_bar(aes(x = Month, fill = Family)) +
  ylab("Count") +
  labs(title = "Total Strandings per Month") +scale_x_discrete(name = "Month",
                   limits = c("Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"))
```


```{r Annual Data Development}
# this code creates a new data frame of the year and number of strandings that year
Annual_Strandings_Sum <- Strandings_Final %>%
  group_by(Year) %>%
  summarise(Sum = n())

# now try to add columns to that data frame of the breakdown of the totals of each group
Annual_Strandings_Turtles <- Strandings_Final %>%
  filter(Family == "Turtles") %>%
  group_by(Year) %>%
  summarise(Turtles_Total = n())

Annual_Strandings_Pinniped <- Strandings_Final %>%
  filter(Family == "Pinnipeds") %>%
  group_by(Year) %>%
  summarise(Pinnipeds_Total = n())

Annual_Strandings_Odontocetes <- Strandings_Final %>%
  filter(Family == "Odontocetes") %>%
  group_by(Year) %>%
  summarise(Odontocetes_Total = n())


Annual_Strandings_Mysticetes <- Strandings_Final %>%
  filter(Family == "Mysticetes") %>%
  group_by(Year) %>%
  summarise(Mysticetes_Total = n()) %>%
  add_row(Year = 1994, Mysticetes_Total=0)



Annual_Strandings_Totals <- cbind(Annual_Strandings_Sum, Annual_Strandings_Turtles[,2], Annual_Strandings_Pinniped[,2], Annual_Strandings_Mysticetes[,2], Annual_Strandings_Odontocetes[,2])

write.csv(Annual_Strandings_Totals, row.names = TRUE, file = "../Data/Processed/annual_strandings_totals.csv")

```


```{r Monthly Data Development}
Monthly_Strandings_Sum <- Strandings_Final %>%
  group_by(Month) %>%
  summarise(Sum = n())

Monthly_Strandings_Turtles <- Strandings_Final %>%
  filter(Family == "Turtles") %>%
  group_by(Month) %>%
  summarise(Turtles_Total = n()) %>%
  add_row(Month = 1, Turtles_Total=0) %>%
  add_row(Month = 10, Turtles_Total=0)


Monthly_Strandings_Pinniped <- Strandings_Final %>%
  filter(Family == "Pinnipeds") %>%
  group_by(Month) %>%
  summarise(Pinnipeds_Total = n())

Monthly_Strandings_Odontocetes <- Strandings_Final %>%
  filter(Family == "Odontocetes") %>%
  group_by(Month) %>%
  summarise(Odontocetes_Total = n())


Monthly_Strandings_Mysticetes <- Strandings_Final %>%
  filter(Family == "Mysticetes") %>%
  group_by(Month) %>%
  summarise(Mysticetes_Total = n()) %>%
  add_row(Month = 1, Mysticetes_Total=0) %>%
  add_row(Month = 10, Mysticetes_Total=0)


Monthly_Strandings_Totals <- cbind(Monthly_Strandings_Sum, Monthly_Strandings_Turtles[,2], Monthly_Strandings_Pinniped[,2], Monthly_Strandings_Mysticetes[,2], Monthly_Strandings_Odontocetes[,2])

write.csv(Monthly_Strandings_Totals, row.names = TRUE, file = "../Data/Processed/monthly_strandings_totals.csv")
```



```{r Geospatial Exploration}
Strandings_sf <- Strandings_Final %>%
  st_as_sf(coords = c("longitude", "latitude"), crs = 4326)

mapview(Strandings_sf, zcol = "Family")
```

