---
output: 
  pdf_document:
    keep_tex: yes
    fig_caption: yes
    number_sections: yes
geometry: margin=2.54cm
title: "Marine Stranding Analysis"
subtitle: "https://github.com/jmeza32/MezaFidalgo_Ozog_Pepper_ENV872_EDA_FinalProject.git"
author: "Joshua Meza-Fidalgo, Jess Ozog & Britney Pepper"
fontsize: 12pt
mainfont: Times New Roman

---

\newpage
\tableofcontents 
\newpage
\listoftables 
\newpage
\listoffigures 
\newpage

```{r setup, include=FALSE}
# Set your working directory

# Load your packages

# Set your ggplot theme

# Load your datasets


```


## Rationale and Research Questions
* Contains clear context for research topic
* Contains rationale for dataset of choice
* Contains one or more questions of an appropriate scope for the project



Aquarium scientists maintain data on marine mammal and sea turtle strandings and sightings as a means of monitoring the behavior and health of these animals, always vigilant for changes in patterns that might signal an unusual event such as a viral outbreak or a toxic algal bloom. The condition of these animals reveals much about the health of our oceans.

Marine animal strandings can be an indicator of the health of our oceans. Seeing patterns in the strandings of marine mammals and sea turtles can be indicative of viral outbreaks or toxic algal blooms. Being able to monitor these animals 
-heath impacts on humans --> it something is harming animals, will it harm us when we comsume seafood
-monitor over the years to see if there were any trends on increases in strandings



\newpage

## Dataset Information
* Describes source and content of data
* Details the wrangling process from raw to processed data
* Contains a table summarizing the dataset structure


Mystic Aquarium's marine mammal and sea turtle stranding data 1976-2011
-contains whales, dolphins, and sea turtles
-number of different species in each family
-datum WGS:1984
-raw data
-output table --> take from data_wrangling file


\newpage

## Exploratory Analysis 
* Flow between text and visualizations is cohesive
* Relevant exploratory information is visualized




\newpage

## Analysis
* Flow between text and visualizations is cohesive
* Visualizations and statistical tests pertain directly to specific questions 
* Statistical results are reported in plain language with relevant statistical output in parentheses 
* Findings are reported clearly in relation to research questions


1. **Pinnipeds**:

*Question 1*: <insert specific question here and add additional subsections for additional questions below, if needed>


2. **Whales**:

*Question 1*: <insert specific question here and add additional subsections for additional questions below, if needed>


3. **Turtles**:

*Question 1*: <insert specific question here and add additional subsections for additional questions below, if needed>




\newpage

## Summary and Conclusions
* Major findings are summarized
* Conclusions relate back to the original research context 




\newpage


## References

**Data**: <https://seamap.env.duke.edu/dataset/945> 

1. Halpin, P.N., A.J. Read, E. Fujioka, B.D. Best, B. Donnelly, L.J. Hazen, C. Kot, K. Urian, E. LaBrecque, A. Dimatteo, J. Cleary, C. Good, L.B. Crowder, and K.D. Hyrenbach. 2009. OBIS-SEAMAP: The world data center for marine mammal, sea bird, and sea turtle distributions. Oceanography. 22(2):104-115.

2. Smith, A. 2014. Mystic Aquarium's marine mammal and sea turtle stranding data 1976-2011. Data downloaded from OBIS-SEAMAP (http://seamap.env.duke.edu/dataset/945) on 2022-04-02.


